#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE readonly;

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO readonly;
  GRANT USAGE ON SCHEMA public TO readonly;
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;

  CREATE USER mcp_readonly WITH PASSWORD '${POSTGRES_MCP_READONLY_PASSWORD}';
  GRANT readonly TO mcp_readonly;
EOSQL