spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.frontend.url=${APP_FRONTEND_URL}

data.products.url=${DATA_PRODUCTS_URL:https://raw.githubusercontent.com/raulHerediaHorcajo/product-distribution-ai/main/data/current/products.json}
data.stores.url=${DATA_STORES_URL:https://raw.githubusercontent.com/raulHerediaHorcajo/product-distribution-ai/main/data/current/stores.json}
data.warehouses.url=${DATA_WAREHOUSES_URL:https://raw.githubusercontent.com/raulHerediaHorcajo/product-distribution-ai/main/data/current/warehouses.json}

scheduler.distribution.cron=3 * * * * *